title: MaryTT
url: http://marytt.com
email: mary.tompkins@gmail.com
availability: available
currentlocation: Irvine, CA
description: The portfolio and blog for web developer and aspiring digital nomad, Mary Tompkins.
keywords: mary, tompkins, mary tompkins, marytt, web developer, seo, freelance, developer

github: marytt
linkedin: mary-tompkins
stackoverflow: 6538634/mary-tompkins

permalink: /blog/:title
excerpt_separator: <!--more-->
markdown: kramdown
