title: Emma Brand
url: http://emmalanebrand.com
email: emmalanebrand@gmail.com
availability: available
currentlocation: Irvine, CA
description: The portfolio and blog for web developer and digital marketer, Emma Brand.
keywords: emma, brand, elbrand, emma lane brand, emma lane, web developer, seo, freelance, developer

github: elbrand
linkedin: emma-brand
stackoverflow: 6538634/emma-brand

permalink: /blog/:title
excerpt_separator: <!--more-->
markdown: kramdown
