title: EBrand
url: http://emmalanebrand.com
email: emmalanebrand@gmail.com
availability: available
currentlocation: Irvine, CA
description: The portfolio and blog for web developer and aspiring digital nomad, Mary Tompkins.
keywords: emma, brand, elbrand, emma lane brand, emma lane, web developer, seo, freelance, developer

github: elbrand
linkedin: mary-tompkins
stackoverflow: 6538634/mary-tompkins

permalink: /blog/:title
excerpt_separator: <!--more-->
markdown: kramdown
